### ISSUE TITLE
Failures: Error: While deploying action: './build.sh' 

### ISSUE THREAD

**Issue by Ser6-IO** [digitalocean/sample-functions-python-sendgrid-email#6]
When deploying via doctl
`doctl serverless deploy`

This Error is returned:
Deploying ...
  to namespace ...
  on host ...
Started running ./build.sh in ...
Output of failed build in 
/bin/bash: ./build.sh: Permission denied

Failures:
**Error**: While deploying action: './build.sh' exited with code 126

**Comment by rabbah** [comment]
the reference to `/bin/bash` is from this here - is `bash` available on your machine?

https://github.com/digitalocean/sample-functions-python-sendgrid-email/blob/93bfe99512717186504106c3f3062b27481bc554/packages/sample/emails/build.sh#L1C1-L1C12

**Comment by Ser6-IO** [comment]
It's working now. I think it was a permissions issue. I had downloaded the code as ZIP, rather than cloning the repo.
I think I solved it with `chmod +x`, but I'm not 100% sure because I changed a few things at the same time.
Thanks,

**Comment by codespearhead** [comment]
Should this issue be closed then?
